# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/mnt/c/Users/nivii/programming/CS degree/year 2/Linux/mtacoin2"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/mnt/c/Users/nivii/programming/CS degree/year 2/Linux/mtacoin2"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/mnt/c/Users/nivii/programming/CS degree/year 2/Linux/mtacoin2/CMakeFiles" "/mnt/c/Users/nivii/programming/CS degree/year 2/Linux/mtacoin2//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/mnt/c/Users/nivii/programming/CS degree/year 2/Linux/mtacoin2/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named funCoin

# Build rule for target.
funCoin: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 funCoin
.PHONY : funCoin

# fast build rule for target.
funCoin/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/funCoin.dir/build.make CMakeFiles/funCoin.dir/build
.PHONY : funCoin/fast

BLOCK_T&Globals.o: BLOCK_T&Globals.cpp.o
.PHONY : BLOCK_T&Globals.o

# target to build an object file
BLOCK_T&Globals.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/funCoin.dir/build.make "CMakeFiles/funCoin.dir/BLOCK_T&Globals.cpp.o"
.PHONY : BLOCK_T&Globals.cpp.o

BLOCK_T&Globals.i: BLOCK_T&Globals.cpp.i
.PHONY : BLOCK_T&Globals.i

# target to preprocess a source file
BLOCK_T&Globals.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/funCoin.dir/build.make "CMakeFiles/funCoin.dir/BLOCK_T&Globals.cpp.i"
.PHONY : BLOCK_T&Globals.cpp.i

BLOCK_T&Globals.s: BLOCK_T&Globals.cpp.s
.PHONY : BLOCK_T&Globals.s

# target to generate assembly for a file
BLOCK_T&Globals.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/funCoin.dir/build.make "CMakeFiles/funCoin.dir/BLOCK_T&Globals.cpp.s"
.PHONY : BLOCK_T&Globals.cpp.s

Miner.o: Miner.cpp.o
.PHONY : Miner.o

# target to build an object file
Miner.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/funCoin.dir/build.make CMakeFiles/funCoin.dir/Miner.cpp.o
.PHONY : Miner.cpp.o

Miner.i: Miner.cpp.i
.PHONY : Miner.i

# target to preprocess a source file
Miner.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/funCoin.dir/build.make CMakeFiles/funCoin.dir/Miner.cpp.i
.PHONY : Miner.cpp.i

Miner.s: Miner.cpp.s
.PHONY : Miner.s

# target to generate assembly for a file
Miner.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/funCoin.dir/build.make CMakeFiles/funCoin.dir/Miner.cpp.s
.PHONY : Miner.cpp.s

Server.o: Server.cpp.o
.PHONY : Server.o

# target to build an object file
Server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/funCoin.dir/build.make CMakeFiles/funCoin.dir/Server.cpp.o
.PHONY : Server.cpp.o

Server.i: Server.cpp.i
.PHONY : Server.i

# target to preprocess a source file
Server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/funCoin.dir/build.make CMakeFiles/funCoin.dir/Server.cpp.i
.PHONY : Server.cpp.i

Server.s: Server.cpp.s
.PHONY : Server.s

# target to generate assembly for a file
Server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/funCoin.dir/build.make CMakeFiles/funCoin.dir/Server.cpp.s
.PHONY : Server.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/funCoin.dir/build.make CMakeFiles/funCoin.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/funCoin.dir/build.make CMakeFiles/funCoin.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/funCoin.dir/build.make CMakeFiles/funCoin.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... funCoin"
	@echo "... BLOCK_T&Globals.o"
	@echo "... BLOCK_T&Globals.i"
	@echo "... BLOCK_T&Globals.s"
	@echo "... Miner.o"
	@echo "... Miner.i"
	@echo "... Miner.s"
	@echo "... Server.o"
	@echo "... Server.i"
	@echo "... Server.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

